sudo: false
language: node_js
matrix:
  include:
    - node_js: "7"
      env: NPM_RUN_SCRIPT=test-coverage
    - node_js: "6"
    - node_js: "5"
    - node_js: "4"
install:
  - npm install
  - if [ -n "$NPM_INSTALL_PACKAGES" ]; then npm install $NPM_INSTALL_PACKAGES; fi
script:
  - npm run ${NPM_RUN_SCRIPT:-test}
