sudo: false
language: node_js
env:
  global:
    TAP_RCFILE=./.taprc
matrix:
  include:
    - node_js: "8"
    - node_js: "7"
    - node_js: "6"
    - node_js: "5"
    - node_js: "4"
install:
  - npm install
  - if [ -n "$NPM_INSTALL_PACKAGES" ]; then npm install $NPM_INSTALL_PACKAGES; fi
  - npm install typescript tslint tslint-config-standard
script:
  - npm run ${NPM_RUN_SCRIPT:-test}
  - node_modules/.bin/tsc
  - node_modules/.bin/tslint -p .
